----------------------------------------------------------
@startuml

title 单元测试系统结构图

package "待测模块" {
    ["模块接口列表"]
}

package "测试代码" {
    ["测试函数列表"]
}

package "外部依赖" {
    ["依赖模块"]
    ["stub/mock"]
}

package "测试报告" {
    ["测试报告"]
}

package "运行环境" {
    ["main 函数"]
    ["makefile"]
    ["编译工具"]
}

["main 函数"] -> ["模块接口列表"]
["main 函数"] -> ["测试函数列表"]
["main 函数"] -> ["依赖模块"]
["main 函数"] -> ["stub/mock"]
["main 函数"] -> ["测试报告"]

@enduml
